name: Reusable Workflow
on:
 workflow_call: 
    inputs:
      name:
        description: 'Input Description'
        type: string
        default: "Ali"
        required: false
    secrets:
      access-token:
        description: 'Secret Description'
        required: true
jobs:
   checkout:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - run: ls -a
   log-context-and-input: 
       runs-on: ubuntu-latest
       steps: 
         - name: Display Github Context
           run: echo '${{ toJson(github)}}'
         - name: Display Name input
           run: echo '${{ inputs.name}}'  
         - name: Display Access Token Secret
           run: echo '${{ secrets.access-token }}'
